[package]
name = "divesync"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "core",
    "cli",
    "ffi",
    "api"
]

[profile.test]
default = ["clippy"]

[dependencies]
serde = "1.0.192"
