[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "divesync-cli"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
clap = { version = "4.4.7", features = ["derive", "cargo"] }
plotters = "0.3.5"
