[package]
name = "core"
version = "0.1.0"
edition = "2021"


[lib]
name = "core"
path = "src/lib.rs"
# crate-type = ["dylib"]

[profile.test]
default = ["clippy"]

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.192", features = ["derive"] }
